alleybookstore/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.urls.conf import include


urlpatterns = [
    path('admin/', admin.site.urls),

    re_path(r'^customer_accounts/', include('customer_accounts.urls')),
    re_path(r'^', include('customer.urls')),
    re_path(r'^seller/', include('seller.urls')),
    re_path(r'^seller_accounts/', include('seller_accounts.urls')),
]

customer_accounts/urls.py
from django.urls import re_path
from .splitviews import *

app_name = 'customer_accounts'

urlpatterns = [
    re_path(r'^login/$', LoginView, name='login'),
    re_path(r'^register/$', RegisterView, name='register'),
    re_path(r'^user-info/(?P<user_id>\d+)/$', InfoModifyView, name='info_modify'),
    re_path(r'^password/(?P<user_id>\d+)/$', PasswordModifyView, name='password_modify'),
    re_path(r'^logout/$', LogoutView, name='logout'),
    re_path(r'^user-info/$', InfoManageView, name='info_manage'),
    re_path(r'^password/$', PasswordCheckView, name='password_check'),
    re_path(r'^secede/$', UserDeleteView, name='user_delete'),
]

seller/urls.py
from django.urls import re_path
from .splitviews import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'seller'

urlpatterns = [
    re_path(r'^$', MainView, name='main'),
    re_path(r'^product/$', ProductListView, name='product_list'),
    re_path(r'^product/book-list$', SearchBookInManageView, name='search_book_in_manage'),
    re_path(r'^product/book-delete/(?P<store_id>\d+)/(?P<isbn>\d+)/$', ProductDeleteView, name='book_delete'),
    re_path(r'^product-modify/$', ProductModifyView, name='book_modify'),
    re_path(r'^product-modify-ajax/(?P<isbn>\d+)/$', AjaxGetProductInfoView, name='book_modify_ajax'),
    re_path(r'^product-register/$', ProductRegisterView, name='product_register'),
    re_path(r'^book-ajax/$', SearchBookAjaxView, name='ajax_book_search'),
    re_path(r'^order/$', OrderCheckView, name='order_check'),
    re_path(r'^pay-check-ajax/(?P<order_num>\d+)/$', PayCheckAjaxView, name='pay_check_ajax'),
    re_path(r'^order-detail-ajax/(?P<order_num>\d+)/$', OrderDetailView, name='order_detail_ajax'),
    re_path(r'^order-return/(?P<click_case>[ㄱ-힣a-zA-Z0-9-_.]*)/$', OrderReturnView, name='order_return'),
    re_path(r'^order-return-check-ajax/(?P<return_id>\d+)/$', OrderReturnCheckAjaxView, name='order_return_check_ajax'),
    re_path(r'^order-return-reject/(?P<return_id>\d+)/$', OrderReturnRejectView, name='order_return_reject'),
    re_path(r'^order-return-reject-compl-ajax/(?P<return_id>\d+)/$', OrderReturnRejectCompAjaxlView, name='order_return_reject_compl_ajax'),
    re_path(r'^book-register/$', BookRegisterView, name='book_register'),
    re_path(r'^delivery/$', DeliveryCheckView, name='delivery_check'),
    re_path(r'^delivery-ajax/(?P<order_num>\d+)/$', DeliveryCheckAjaxView, name='delivery_check_ajax'),
    re_path(r'^notice/$', NoticeForCustomerView, name='notice'),
    re_path(r'^notice-delete/(?P<notice_id>\d+)/$', NoticeDeleteView, name='notice_delete'),
    re_path(r'^notice-modify-ajax/(?P<notice_id>\d+)/$', AjaxGetNoticeView, name='notice_modify_ajax'),
    re_path(r'^settlement/$', SettlementCheckView, name='settlement_check'),
    re_path(r'^monthly-settlement/$', MonthlySettlementView, name='monthly_settlement'),
    re_path(r'^frequent-question/$', FrequentQuestionView, name='frequent_question'),
    re_path(r'^frequent-question-delete/(?P<faq_id>\d+)/$', FrequentQuestionDeleteView, name='frequent_question_delete'),
    re_path(r'^frequent-question-modify/(?P<faq_id>\d+)/$', FrequentQuestionModifyView, name='frequent_question_modify'),
    re_path(r'^individual-question/(?P<store_id>\d+)/$', IndividualQuestionView, name='individual_question'),
    re_path(r'^individual-question-answer/(?P<question_id>\d+)/$', IndividualQuestionAnswerView, name='individual_question_answer'),
    re_path(r'^review/$', ReviewManageView, name='review_manage'),
    re_path(r'^review-answer/$', ReviewAnswerView, name='review_answer'),
    re_path(r'^review-answer-ajax/(?P<review_id>\d+)/$', AjaxGetReviewAnswerView, name='answer_modify_ajax'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seller_accounts/urls.py
from django.urls import re_path
from .splitviews import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'seller_accounts'

urlpatterns = [
    re_path(r'^seller_register/$', SellerRegisterView, name='seller_register'),
    re_path(r'^bookstore_register/$', BookStoreRegisterView, name='bookstore_register'),
    re_path(r'^shipping_info_register/$', ShippingInfoRegisterView, name='shipping_info_register'),
    re_path(r'^seller_login/$', SellerLoginView, name='seller_login'),
    re_path(r'^seller_info/$', SellerInfoView, name='seller_info'),
    re_path(r'^seller_info/bookstore/(?P<user_id>\d+)/$', BookstoreModifyView, name='bookstore_modify'),
    re_path(r'^seller_info/shipping_info/$', ShippingInfoModifyView, name='shipping_info_modify'),
    re_path(r'^secede/$', SellerDeleteView, name='seller_delete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seller_accounts/views.py
from django.shortcuts import render

# Create your views here.

seller_accounts/templates/bookstore_modify.html
    <div class="row justify-content-center align-items-center">
        <div style="margin-top:100px;">
        <div class="card">
          <h4 class="card-header">서점 정보 수정</h4>
        <div class="card-body">
        <div class="text-center">
            {% if messages %}
                {% for message in messages %}
                  <p style="color:red"> {{message.message}} </p>
                {% endfor %}
            {% endif %}
          <img class="" src="">
        </div>
        <form class="mt-3" method="post" action='{% url "seller_accounts:bookstore_modify" user.id %}' enctype="multipart/form-data">{% csrf_token %}
            <div class="form-group">
              서점 이름<input type="text" class="form-control" id="name" name="store_name" placeholder="서점 이름" value="{{ store.store_name }}">
            </div>
            <div class="form-group">
              대표자 이름<input type="text" class="form-control" id="user_id" name="repre_name" placeholder="대표자 이름" value="{{ store.repre_name }}">
            </div>
            <div class="form-group">
              서점 주소<input type="text" class="form-control" id="address" name="address" placeholder="서점 주소" value="{{ store.address }}">
            </div>
            <div class="form-group">
              서점 연락처<input type="tel" class="form-control" id="store_number" name="store_number"
                     pattern="(010)-\d{3,4}-\d{4}" placeholder="서점 연락처 ex) 010-1234-1234" value="{{ store.store_num }}">
            </div>
            <div class="form-group">
              서점 E-Mail<input type="email" class="form-control" id="e_mail" name="e_mail" placeholder="서점 E-Mail" value="{{ store.store_email }}">
            </div>
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroupFileAddon01">서점 이미지</span>
              </div>
              <div class="custom-file">
                <input type="file" class="custom-file-input" id="store_img" name="store_img" aria-describedby="inputGroupFileAddon01" value="{{ store.store_img }}">
                <label class="custom-file-label" for="store_img">파일을 선택해주세요.</label>
              </div>
            </div>
            <div class="form-group">
              서점 소개글<input type="text" class="form-control" id="store_msg" name="store_msg" placeholder="서점 소개글" value="{{ store.store_msg }}">
            </div>
            <button type="submit" class="btn btn-primary" onclick="info_modify()">수정 완료</button>
        </form>
        </div>
        </div>
        </div>
    </div>

<script type="text/javascript">
    function info_modify(){
        if (confirm("입력한 정보를 수정하시겠습니까?") == true){
            document.form.submit();
        }else{
            alert('취소되었습니다.');
            event.preventDefault();
        }
    }

    window.onpageshow = function(event) {
        if ( event.persisted || (window.performance && window.performance.navigation.type == 2)) {
            // Back Forward Cache로 브라우저가 로딩될 경우 혹은 브라우저 뒤로가기 했을 경우
            alert('제출 양식이 만료되었습니다.');
            history.back();
        }
    }
</script>

seller_accounts/templates/bookstore_registration.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
{% endblock head %}

{% block title %}
서점 등록 | alleybookstore
{% endblock title %}

{% block _nav %}
  {% include '_seller_nav.html' %}
{% endblock _nav %}

{% block body %}
<div class="container">
    <div class="row justify-content-center align-items-center">
        <div style="margin-top:100px;">
        <div class="card">
          <h4 class="card-header">서점 등록</h4>
        <div class="card-body">
        <div class="text-center">
            {% if messages %}
                {% for message in messages %}
                  <p style="color:red"> {{message.message}} </p>
                {% endfor %}
            {% endif %}
          <img class="" src="">
        </div>
        <form class="mt-3" method="post" action='{% url "seller_accounts:bookstore_register" %}' enctype="multipart/form-data">{% csrf_token %}
            <div class="form-group">
              <input type="text" class="form-control" id="business_num" name="business_num" placeholder="사업자번호" required>
            </div>
            <div class="form-group">
              <input type="text" class="form-control" id="name" name="store_name" placeholder="서점 이름" required>
            </div>
            <div class="form-group">
              <input type="text" class="form-control" id="user_id" name="repre_name" placeholder="대표자 이름" required>
            </div>
            <div class="form-group">
              <input type="text" class="form-control" id="address" name="address" placeholder="서점 주소" required>
            </div>
            <div class="form-group">
              <input type="tel" class="form-control" id="store_number" name="store_number"
                     pattern="(010)-\d{3,4}-\d{4}" placeholder="서점 연락처 ex) 010-1234-1234" required>
            </div>
            <div class="form-group">
              <input type="email" class="form-control" id="e_mail" name="e_mail" placeholder="서점 E-Mail">
            </div>
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroupFileAddon01">Upload</span>
              </div>
              <div class="custom-file">
                <input type="file" class="custom-file-input" id="store_img" name="store_img" aria-describedby="inputGroupFileAddon01">
                <label class="custom-file-label" for="store_img">파일을 선택해주세요.</label>
              </div>
            </div>
            <div class="form-group">
              <input type="text" class="form-control" id="store_msg" name="store_msg" placeholder="서점 소개글">
            </div>
            <button type="submit" class="btn btn-primary" onclick="alert('서점 등록을 완료하시겠습니까?')">서점등록</button>
        </form>
        </div>
        </div>
        </div>
    </div>
</div>

{% block footer %}
{% include 'footer.html' %}
{% endblock footer %}

{% endblock body %}

seller_accounts/templates/seller_delete.html
    <div class="row justify-content-center align-items-center">
        <div style="margin-top:100px;">
        <div class="card">
          <h4 class="card-header">회원탈퇴</h4>
        <div class="card-body">

        <div class="text-center mt-3">
           <b>본인확인을 위해 ID와 비밀번호를 입력해주세요</b><br><br>
        </div>

        <div class="text-center">
            {% if messages %}
                {% for message in messages %}
                  <p style="color:red"> {{message.message}} </p>
                {% endfor %}
            {% endif %}
          <img class="" src="">
        </div>

        <form class="mt-3" method="post" action='{% url "seller_accounts:seller_delete" %}'>{% csrf_token %}
            <div class="form-group">
              <input type="text" class="form-control" id="id" name="id" placeholder="ID">
            </div>
            <div class="form-group">
              <input type="password" class="form-control" id="password" name="password" placeholder="비밀번호">
            </div>
            <button type="submit" class="btn btn-primary" onclick="user_delete()">회원탈퇴</button>
        </form>
        </div>
        </div>
        </div>
    </div>


<script type="text/javascript">
    function user_delete(){
        if (confirm("정말로 탈퇴하시겠습니까?") == true){
            document.form.submit();
        }else{
            event.preventDefault();
        }
    }

    window.onpageshow = function(event) {
        if ( event.persisted || (window.performance && window.performance.navigation.type == 2)) {
            // Back Forward Cache로 브라우저가 로딩될 경우 혹은 브라우저 뒤로가기 했을 경우
            alert('제출 양식이 만료되었습니다.');
            history.back();
        }
    }

</script>

seller_accounts/templates/seller_info.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/accounts.css' %}">
{% endblock head %}

{% block title %}
마이페이지 | alleybookstore
{% endblock title %}

{% block _nav %}
  {% include '_seller_nav.html' %}
{% endblock _nav %}

{% block body %}
<div class="container">
<div class="tab_wrap">
  {% if tab_is == 0 %}
    <div class="tab_menu_container">
      <button class="tab_menu_btn on" type="button">서점 정보 수정</button>
      <button class="tab_menu_btn" type="button">배송 정보 수정</button>
      <button class="tab_menu_btn" type="button">비밀번호 수정</button>
      <button class="tab_menu_btn" type="button">판매자 탈퇴</button>
    </div> <!-- tab_menu_container e -->

    <div class="tab_box_container">
      <div class="tab_box on">{% include 'bookstore_modify.html' %}</div>
      <div class="tab_box">{% include 'shipping_info_modify.html' %}</div>
      <div class="tab_box">{% include 'seller_password_modify.html' %}</div>
      <div class="tab_box">{% include 'seller_delete.html' %}</div>
    </div> <!-- tab_box_container e -->
  {% elif tab_is == 1 %}
    <div class="tab_menu_container">
      <button class="tab_menu_btn" type="button">서점 정보 수정</button>
      <button class="tab_menu_btn" type="button">배송 정보 수정</button>
      <button class="tab_menu_btn on" type="button">비밀번호 수정</button>
      <button class="tab_menu_btn" type="button">판매자 탈퇴</button>
    </div> <!-- tab_menu_container e -->

    <div class="tab_box_container">
      <div class="tab_box">{% include 'bookstore_modify.html' %}</div>
      <div class="tab_box">{% include 'shipping_info_modify.html' %}</div>
      <div class="tab_box on">{% include 'seller_password_modify.html' %}</div>
      <div class="tab_box">{% include 'seller_delete.html' %}</div>
    </div> <!-- tab_box_container e -->
  {% elif tab_is == 2  %}
    <div class="tab_menu_container">
      <button class="tab_menu_btn" type="button">서점 정보 수정</button>
      <button class="tab_menu_btn" type="button">배송 정보 수정</button>
      <button class="tab_menu_btn" type="button">비밀번호 수정</button>
      <button class="tab_menu_btn on" type="button">판매자 탈퇴</button>
    </div> <!-- tab_menu_container e -->

    <div class="tab_box_container">
      <div class="tab_box">{% include 'bookstore_modify.html' %}</div>
      <div class="tab_box">{% include 'shipping_info_modify.html' %}</div>
      <div class="tab_box">{% include 'seller_password_modify.html' %}</div>
      <div class="tab_box on">{% include 'seller_delete.html' %}</div>
    </div> <!-- tab_box_container e -->
  {% endif %}
</div> <!-- tab_wrap e -->
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript">
    $('.tab_menu_btn').on('click',function(){
  //버튼 색 제거,추가
  $('.tab_menu_btn').removeClass('on');
  $(this).addClass('on')

  //컨텐츠 제거 후 인덱스에 맞는 컨텐츠 노출
  var idx = $('.tab_menu_btn').index(this);

  $('.tab_box').hide();
  $('.tab_box').eq(idx).show();
});
</script>

{% block footer %}
{% include 'footer.html' %}
{% endblock footer %}

{% endblock body %}

seller_accounts/templates/seller_login.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/accounts.css' %}">
{% endblock head %}

{% block title %}
판매자 로그인 | alleybookstore
{% endblock title %}

{% block _nav %}
  {% include '_nav.html' %}
{% endblock _nav %}

{% block body %}
<div class="container">
    <div class="row justify-content-center align-items-center">
        <div style="margin-top:100px;">
            <h4 align="center">판매자 로그인 후 이용하실 수 있습니다.</h4>
        <div class="card">
          <h4 class="card-header">로그인</h4>
        <div class="card-body">
        <div class="text-center">
            {% if messages %}
                {% for message in messages %}
                  <p style="color:red"> {{message.message}} </p>
                {% endfor %}
            {% endif %}
          <img class="" src="">
        </div>
        <form class="mt-3" method="post" action='{% url "customer_accounts:login" %}'>{% csrf_token %}
            <div class="form-group">
              <input type="text" class="form-control" id="user_id" name="user_id" placeholder="사용자 ID">
            </div>
            <div class="form-group">
              <input type="password" class="form-control" id="user_pw" name="user_pw" placeholder="비밀번호">
            </div>
            <button type="submit" class="btn btn-primary" onclick="">Login</button>
        </form>
        </div>
        </div>
        <div class="card mt-2">
        <div class="text-center mt-3">
          <p>판매자 계정이 없으신가요? <a href='{% url "seller_accounts:seller_register" %}'> 판매자 회원가입</a></p>
        </div>
        </div>
        </div>
    </div>
</div>

{% block footer %}
{% include 'footer.html' %}
{% endblock footer %}

{% endblock body %}

seller_accounts/templates/seller_password_modify.html
    <div class="row justify-content-center align-items-center">
        <div style="margin-top:100px;">
        <div class="card">
          <h4 class="card-header">비밀번호 변경</h4>
        <div class="card-body">
        <div class="text-center">
            {% if messages %}
                {% for message in messages %}
                  <p style="color:red"> {{message.message}} </p>
                {% endfor %}
            {% endif %}
          <img class="" src="">
        </div>
        <form class="mt-3" method="post" action='{% url "customer_accounts:password_modify" user.id %}'>{% csrf_token %}
            <div class="form-group">
              <input type="password" class="form-control" id="current_password" name="current_password" placeholder="현재 비밀번호">
            </div>
            <div class="form-group">
              <input type="password" class="form-control" id="new_password" name="new_password" placeholder="새 비밀번호">
            </div>
            <div class="form-group">
              <input type="password" class="form-control" id="check_new_password" name="check_new_password" placeholder="새 비밀번호 확인">
            </div>
            <button type="submit" class="btn btn-primary" onclick="password_modify()">수정 완료</button>
        </form>
        </div>
        </div>
        </div>
    </div>

<script type="text/javascript">
    function password_modify(){
        if (confirm("비밀번호를 변경하시겠습니까?") == true){
            document.form.submit();
        }else{
            event.preventDefault();
        }
    }

    window.onpageshow = function(event) {
        if ( event.persisted || (window.performance && window.performance.navigation.type == 2)) {
            // Back Forward Cache로 브라우저가 로딩될 경우 혹은 브라우저 뒤로가기 했을 경우
            alert('제출 양식이 만료되었습니다.');
            history.back();
        }
    }

</script>

seller_accounts/templates/seller_register.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/accounts.css' %}">
{% endblock head %}

{% block title %}
판매자 회원가입 | alleybookstore
{% endblock title %}

{% block _nav %}
  {% include '_nav.html' %}
{% endblock _nav %}

{% block body %}
<div class="container">
    <div class="row justify-content-center align-items-center">
        <div style="margin-top:100px;">
        <div class="card">
          <h4 class="card-header">판매자 회원가입</h4>
        <div class="card-body">
        <div class="text-center">
            {% if messages %}
                {% for message in messages %}
                  <p style="color:red"> {{message.message}} </p>
                {% endfor %}
            {% endif %}
          <img class="" src="">
        </div>
        <form class="mt-3" method="post" action='{% url "seller_accounts:seller_register" %}'>{% csrf_token %}
            <div class="form-group">
              <input type="text" class="form-control" id="name" name="name" placeholder="성명" required>
            </div>
            <div class="form-group">
              <input type="text" class="form-control" id="user_id" name="user_id" placeholder="사용자 ID" required>
            </div>
            <div class="form-group">
              <input type="password" class="form-control" id="user_pw" name="user_pw" placeholder="비밀번호" required>
            </div>
            <div class="form-group">
              <input type="password" class="form-control" id="user_2nd_pw" name="user_2nd_pw" placeholder="비밀번호 재입력" required>
            </div>
            <button type="submit" class="btn btn-primary" onclick="alert('회원가입을 완료하시겠습니까?')">회원가입</button>
        </form>
        </div>
        </div>
        <div class="card mt-2">
        <div class="text-center mt-3">
          <p>이미 계정이 있으신가요? <a href='{% url "customer_accounts:login" %}'>로그인</a></p>
        </div>
        </div>
        </div>
    </div>
</div>

{% block footer %}
{% include 'footer.html' %}
{% endblock footer %}

{% endblock body %}

seller_accounts/templates/shipping_info_modify.html
    <div class="row justify-content-center align-items-center">
        <div style="margin-top:100px;">
        <div class="card">
          <h4 class="card-header">배송 정보 수정</h4>
        <div class="card-body">
        <div class="text-center">
            {% if messages %}
                {% for message in messages %}
                  <p style="color:red"> {{message.message}} </p>
                {% endfor %}
            {% endif %}
        </div>
        <form class="mt-3" method="post" action='{% url "seller_accounts:shipping_info_modify" %}' enctype="multipart/form-data">{% csrf_token %}
            <div class="form-group">
            <p>현재 배송정책</p>
            <p><input type="radio" name="shipping_policy" value="{{shipping_info.shipping_policy}}" checked>{{shipping_info.shipping_policy}}</p>
            <p>변경할 배송정책</p>
                <p><input type="radio" name="shipping_policy" value="택배 배송">택배 배송</p>
                <p><input type="radio" name="shipping_policy" value="무료 배송">무료 배송</p>
            </div>
            <div class="form-group">
              <input type="text" class="form-control" id="send_address" name="send_address" placeholder="출고지 주소" value="{{ shipping_info.send_address }}" required>
            </div>
            <div class="form-group">
              <input type="text" class="form-control" id="return_address" name="return_address" placeholder="반품/교환지 주소" value="{{ shipping_info.return_address }}" required>
            </div>
            <p>현재 설정된 은행</p>
            <p><input type="radio" name="bank" value="{{shipping_info.bank}}" checked>{{shipping_info.bank}}</p>
            <p>변경할 은행</p>
            <div class="flex order">
                <p><input type="radio" name="bank" value="국민">국민</p>
                <p><input type="radio" name="bank" value="신한">신한</p>
                <p><input type="radio" name="bank" value="농협">농협</p>
                <p><input type="radio" name="bank" value="우리">우리</p>
                <p><input type="radio" name="bank" value="하나">하나</p>
                <p><input type="radio" name="bank" value="기업">기업</p>
                <p><input type="radio" name="bank" value="카카오">카카오</p>
            </div>
            <div class="form-group">
              <input type="text" class="form-control" id="bank_account" name="bank_account" placeholder="계좌번호" value="{{ shipping_info.account }}" required>
            </div>
            <button type="submit" class="btn btn-primary" onclick="info_modify()">수정 완료</button>
        </form>
        </div>
        </div>
        </div>
    </div>

<script type="text/javascript">
    function info_modify(){
        if (confirm("입력한 정보를 수정하시겠습니까?") == true){
            document.form.submit();
        }else{
            alert('취소되었습니다.');
            event.preventDefault();
        }
    }

    window.onpageshow = function(event) {
        if ( event.persisted || (window.performance && window.performance.navigation.type == 2)) {
            // Back Forward Cache로 브라우저가 로딩될 경우 혹은 브라우저 뒤로가기 했을 경우
            alert('제출 양식이 만료되었습니다.');
            history.back();
        }
    }
</script>

seller_accounts/templates/shipping_info_registration.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
{% endblock head %}

{% block title %}
배송 정보 등록 | alleybookstore
{% endblock title %}

{% block _nav %}
  {% include '_seller_nav.html' %}
{% endblock _nav %}

{% block body %}
<div class="container">
    <div class="row justify-content-center align-items-center">
        <div style="margin-top:100px;">
        <div class="card">
          <h4 class="card-header">배송 정보 등록</h4>
        <div class="card-body">
        <div class="text-center">
            {% if messages %}
                {% for message in messages %}
                  <p style="color:red"> {{message.message}} </p>
                {% endfor %}
            {% endif %}
        </div>
        <form class="mt-3" method="post" action='{% url "seller_accounts:shipping_info_register" %}' enctype="multipart/form-data">{% csrf_token %}
            <h4>배송정보</h4>
            <div class="form-group">
              <p>배송 정책</p>
                <p><input type="radio" name="shipping_policy" value="택배 배송" checked>택배 배송</p>
                <p><input type="radio" name="shipping_policy" value="무료 배송">무료 배송</p>
            </div>
            <div class="form-group">
              <input type="text" class="form-control" id="send_address" name="send_address" placeholder="출고지 주소" required>
            </div>
            <div class="form-group">
              <input type="text" class="form-control" id="return_address" name="return_address" placeholder="반품/교환지 주소" required>
            </div>
            <p>은행</p>
            <div class="flex order">
                <p><input type="radio" name="bank" value="국민" checked>국민</p>
                <p><input type="radio" name="bank" value="신한">신한</p>
                <p><input type="radio" name="bank" value="농협">농협</p>
                <p><input type="radio" name="bank" value="우리">우리</p>
                <p><input type="radio" name="bank" value="하나">하나</p>
                <p><input type="radio" name="bank" value="기업">기업</p>
                <p><input type="radio" name="bank" value="카카오">카카오</p>
            </div>
            <div class="form-group">
              <input type="text" class="form-control" id="bank_account" name="bank_account" placeholder="계좌번호" required>
            </div>
            <button type="submit" class="btn btn-primary" onclick="alert('서점 등록을 완료하시겠습니까?')">서점등록</button>
        </form>
        </div>
        </div>
        </div>
    </div>
</div>

{% block footer %}
{% include 'footer.html' %}
{% endblock footer %}

{% endblock body %}