alleybookstore/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.urls.conf import include


urlpatterns = [
    path('admin/', admin.site.urls),

    re_path(r'^customer_accounts/', include('customer_accounts.urls')),
    re_path(r'^', include('customer.urls')),
    re_path(r'^seller/', include('seller.urls')),
    re_path(r'^seller_accounts/', include('seller_accounts.urls')),
]

customer/urls.py
from django.urls import re_path
from .splitviews import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'customer'

urlpatterns = [
    re_path(r'^$', MainView, name='main'),
    re_path(r'^bookstore/$', SearchStoreView, name='search_store'),
    re_path(r'^bookstore/region/$', RegionSearchView, name='region_search'),
    re_path(r'^bookstore/keyword/$', KeywordSearchView, name='keyword_search'),
    re_path(r'^bookstore/(?P<store_id>\d+)/$', BookStoreDetailView, name='bookstore_detail'),
    re_path(r'^book/$', SearchBookView, name='search_book'),
    re_path(r'^book-list/$', SearchBookResultView, name='search_book_result'),
    re_path(r'^mypage/$', MyPageView, name='mypage'),
    re_path(r'^ajax-city/$', AjaxGetCityView, name='ajax_get_city'),
    re_path(r'^book/(?P<book_isbn>\d+)/(?P<store_id>\d+)/$', BookDetailView, name='book_detail'),
    re_path(r'^book/(?P<book_isbn>\d+)/(?P<store_id>\d+)/customer/$', BookLikeView, name='book_like'),
    re_path(r'^favorite/(?P<store_id>\d+)/$', FavoriteView, name='favorite'),
    re_path(r'^unfavorite/(?P<store_id>\d+)/$', UnfavoriteView, name='unfavorite'),
    re_path(r'^review/(?P<book_isbn>\d+)/(?P<store_id>\d+)/$', BookReviewView, name='book_review'),
    re_path(r'^review/(?P<review_id>\d+)/user/$', BookReviewDeleteView, name='book_review_delete'),
    re_path(r'^review/(?P<review_id>\d+)/modify/$', BookReviewModifyView, name='book_review_modify'),
    re_path(r'^review-ajax-recent/(?P<book_isbn>\d+)/$', AjaxReviewRecentView, name='ajax_review_recent'),
    re_path(r'^review-ajax-highScore/(?P<book_isbn>\d+)/$', AjaxReviewHighScoreView, name='ajax_review_high_score'),
    re_path(r'^basket/(?P<book_isbn>\d+)/(?P<store_id>\d+)/$', BookBasketInsertView, name='book_basket_insert'),
    re_path(r'^basket/(?P<book_isbn>\d+)/session/$', BookBasketDeleteView, name='book_basket_delete'),
    re_path(r'^book/category/$', CategoryView, name='category'),
    re_path(r'^book/category/(?P<main_category_id>\d+)/$', CategoryResultView, name='category_book'),
    re_path(r'^order-sheet/(?P<book_isbn>\d+)/(?P<store_id>\d+)/$', OrderSheetView, name='order_sheet'),
    re_path(r'^order-sheet/cart/$', OrderSheetCartView, name='order_sheet_cart'),
    re_path(r'^order-sheet/create/$', OrderCreateView, name='order'),
    re_path(r'^order-confirm/(?P<order_num>\d+)/$', OrderConfirmView, name='order_confirm'),
    re_path(r'^order-detail/(?P<order_num>\d+)/$', OrderDetailView, name='order_detail'),
    re_path(r'^order-history/$', OrderHistoryView, name='order_history'),
    re_path(r'^bookstore/book-list/$', SearchBookInStoreView, name='search_book_in_store'),
    re_path(r'^mypage_basket/$', CustomerBasketView, name='mypage_basket'),
    re_path(r'^order-decision/(?P<order_num>\d+)/$', OrderDecisionView, name='order_decision'),
    re_path(r'^order-cancel/(?P<order_num>\d+)/$', OrderCancelView, name='order_cancel'),
    re_path(r'^product-return/(?P<order_id>\d+)/$', ProductReturnView, name='product_return'),
    re_path(r'^frequently-question/(?P<store_id>\d+)/$', FrequentQuestionView, name='frequent_question'),
    re_path(r'^individual-question/(?P<store_id>\d+)/$', IndividualQuestionView, name='individual_question'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer_accounts/urls.py
from django.urls import re_path
from .splitviews import *

app_name = 'customer_accounts'

urlpatterns = [
    re_path(r'^login/$', LoginView, name='login'),
    re_path(r'^register/$', RegisterView, name='register'),
    re_path(r'^user-info/(?P<user_id>\d+)/$', InfoModifyView, name='info_modify'),
    re_path(r'^password/(?P<user_id>\d+)/$', PasswordModifyView, name='password_modify'),
    re_path(r'^logout/$', LogoutView, name='logout'),
    re_path(r'^user-info/$', InfoManageView, name='info_manage'),
    re_path(r'^password/$', PasswordCheckView, name='password_check'),
    re_path(r'^secede/$', UserDeleteView, name='user_delete'),
]

seller/urls.py
from django.urls import re_path
from .splitviews import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'seller'

urlpatterns = [
    re_path(r'^$', MainView, name='main'),
    re_path(r'^product/$', ProductListView, name='product_list'),
    re_path(r'^product/book-list$', SearchBookInManageView, name='search_book_in_manage'),
    re_path(r'^product/book-delete/(?P<store_id>\d+)/(?P<isbn>\d+)/$', ProductDeleteView, name='book_delete'),
    re_path(r'^product-modify/$', ProductModifyView, name='book_modify'),
    re_path(r'^product-modify-ajax/(?P<isbn>\d+)/$', AjaxGetProductInfoView, name='book_modify_ajax'),
    re_path(r'^product-register/$', ProductRegisterView, name='product_register'),
    re_path(r'^book-ajax/$', SearchBookAjaxView, name='ajax_book_search'),
    re_path(r'^order/$', OrderCheckView, name='order_check'),
    re_path(r'^pay-check-ajax/(?P<order_num>\d+)/$', PayCheckAjaxView, name='pay_check_ajax'),
    re_path(r'^order-detail-ajax/(?P<order_num>\d+)/$', OrderDetailView, name='order_detail_ajax'),
    re_path(r'^order-return/(?P<click_case>[ㄱ-힣a-zA-Z0-9-_.]*)/$', OrderReturnView, name='order_return'),
    re_path(r'^order-return-check-ajax/(?P<return_id>\d+)/$', OrderReturnCheckAjaxView, name='order_return_check_ajax'),
    re_path(r'^order-return-reject/(?P<return_id>\d+)/$', OrderReturnRejectView, name='order_return_reject'),
    re_path(r'^order-return-reject-compl-ajax/(?P<return_id>\d+)/$', OrderReturnRejectCompAjaxlView, name='order_return_reject_compl_ajax'),
    re_path(r'^book-register/$', BookRegisterView, name='book_register'),
    re_path(r'^delivery/$', DeliveryCheckView, name='delivery_check'),
    re_path(r'^delivery-ajax/(?P<order_num>\d+)/$', DeliveryCheckAjaxView, name='delivery_check_ajax'),
    re_path(r'^notice/$', NoticeForCustomerView, name='notice'),
    re_path(r'^notice-delete/(?P<notice_id>\d+)/$', NoticeDeleteView, name='notice_delete'),
    re_path(r'^notice-modify-ajax/(?P<notice_id>\d+)/$', AjaxGetNoticeView, name='notice_modify_ajax'),
    re_path(r'^settlement/$', SettlementCheckView, name='settlement_check'),
    re_path(r'^monthly-settlement/$', MonthlySettlementView, name='monthly_settlement'),
    re_path(r'^frequent-question/$', FrequentQuestionView, name='frequent_question'),
    re_path(r'^frequent-question-delete/(?P<faq_id>\d+)/$', FrequentQuestionDeleteView, name='frequent_question_delete'),
    re_path(r'^frequent-question-modify/(?P<faq_id>\d+)/$', FrequentQuestionModifyView, name='frequent_question_modify'),
    re_path(r'^individual-question/(?P<store_id>\d+)/$', IndividualQuestionView, name='individual_question'),
    re_path(r'^individual-question-answer/(?P<question_id>\d+)/$', IndividualQuestionAnswerView, name='individual_question_answer'),
    re_path(r'^review/$', ReviewManageView, name='review_manage'),
    re_path(r'^review-answer/$', ReviewAnswerView, name='review_answer'),
    re_path(r'^review-answer-ajax/(?P<review_id>\d+)/$', AjaxGetReviewAnswerView, name='answer_modify_ajax'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seller_accounts/urls.py
from django.urls import re_path
from .splitviews import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'seller_accounts'

urlpatterns = [
    re_path(r'^seller_register/$', SellerRegisterView, name='seller_register'),
    re_path(r'^bookstore_register/$', BookStoreRegisterView, name='bookstore_register'),
    re_path(r'^shipping_info_register/$', ShippingInfoRegisterView, name='shipping_info_register'),
    re_path(r'^seller_login/$', SellerLoginView, name='seller_login'),
    re_path(r'^seller_info/$', SellerInfoView, name='seller_info'),
    re_path(r'^seller_info/bookstore/(?P<user_id>\d+)/$', BookstoreModifyView, name='bookstore_modify'),
    re_path(r'^seller_info/shipping_info/$', ShippingInfoModifyView, name='shipping_info_modify'),
    re_path(r'^secede/$', SellerDeleteView, name='seller_delete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seller/models.py
from django.db import models

# Create your models here.

seller/templates/_seller_nav.html
{% load static %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/_nav.css' %}">
{% endblock head %}
<header>
  <nav class="navbar  navbar-fixed-top navbar-default">
    <div class="container">
      <div class="collapse navbar-collapse" id="navbar-collapse-uarr" >
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'seller:main' %}" title="" class="active">판매자 홈</a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'seller:product_register' %}" title="">상품등록</a></li>
          <li><a href="{% url 'seller:order_check' %}" title="">주문확인 요청</a></li>
          <li><a href="{% url 'seller:product_list' %}" title="">상품 및 재고 관리</a></li>
          <li><a href="{% url 'seller:delivery_check' %}" title="">배송관리</a></li>
          <li><a href="{% url 'seller:settlement_check' %}" title="">정산조회</a></li>
          <li><a href="{% url 'seller:order_return' 'all' %}" title="">반품관리</a></li>
          {% endif %}
          {% if user.is_authenticated and user.user_type == 3 %}
          <li><a href="{% url 'seller_accounts:seller_info' %}" title="">마이페이지</a></li>
            <li>
              <p>
                <a href="{% url 'customer_accounts:logout' %}" class="btn btn-primary navbar-btn" title="">로그아웃</a>
              </p>
            </li>
          {% else %}
            <li>
              <p>
                <a href="{% url 'seller_accounts:seller_login' %}" class="btn btn-primary navbar-btn" title="">로그인</a>
              </p>
            </li>
          {% endif %}

        </ul>
      </div>
    </div>
  </nav>
</header>

seller/templates/delivery_check.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/order.css' %}">
{% endblock head %}

{% block title %}
배송 상태 확인 | alleybookstore
{% endblock title %}

{% block _nav %}
  {% include '_seller_nav.html' %}
{% endblock _nav %}

{% block body %}
<div class="container">
    <div class="row justify-content-center align-items-center">
        <div align="center" style="margin-top:100px;">
            <table class="order_history">
                <tr class="order_history_tr">
                    <th class="order_history_th" width="190">주문번호</th>
                    <th class="order_history_th" width="250">주문날짜</th>
                    <th class="order_history_th" width="150">결제금액</th>
                    <th class="order_history_th" width="100">
                        <form class="mt-3" method="post" enctype="multipart/form-data" action='{% url "seller:delivery_check" %}'>{% csrf_token %}
                              <select id="order_status" name="order_status">
                                <option value="">배송 상태별</option>
                                <option value="결제 완료">결제 완료</option>
                                <option value="배송 준비">배송 준비</option>
                                <option value="배송 중">배송 중</option>
                                <option value="배송 완료">배송 완료</option>
                              </select>
                            <button class="btn btn-primary" type="submit">조회</button>
                        </form>
                    </th>
                    <th class="order_history_th" width="100">확인버튼</th>
                </tr>
                {% for data in delivery_info %}
                <tr class="order_history_tr">
                    <td class="order_history_td" width="190">{{ data.order_num }}</a></td>
                    <td class="order_history_td" width="100">{{ data.buy_date }}</td>
                    <td class="order_history_td" width="250">{{ data.purchased_price }} 원</td>
                    <td class="order_history_td" width="250">{{ data.order_status }}</td>
                    <td class="order_history_td" width="250">
                        {% if data.order_status == "결제 완료" %}
                                <button class="after_button" onclick="delivery_check(this, '{{ data.order_num }}')">주문 확인</button>
                        {% elif data.order_status == "배송 준비" %}
                                <button class="after_button" onclick="delivery_check(this, '{{ data.order_num }}')">상품 인계</button>
                        {% elif data.order_status == "배송 중" %}
                                <button class="after_button">배송 중</button>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>

{% block footer %}
{% include 'footer.html' %}
{% endblock footer %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript" src="https://code.jquery.com/jquery-1.12.4.min.js" ></script>
<script type="text/javascript">
function delivery_check(elm, n) {
        $.ajax({
            url: "{% url 'seller:delivery_check_ajax' 1 %}".replace("1",n),
            data: {'csrfmiddlewaretoken': '{{csrf_token}}'},
            dataType: "json",
            type: "POST",
            success: function(response){
                if (response.update_order_status == "배송 준비"){
                    $(elm).parent().prev().text("배송 준비");
                    $(elm).attr("onclick", "delivery_check(this, '" + n + "')");
                    $(elm).attr("class", "after_button");
                    $(elm).text("주문 확인");
                    alert('배송 준비로 변경되었습니다.');
                }
                else if (response.update_order_status == "배송 중"){
                    $(elm).parent().prev().text("배송 중");
                    $(elm).attr("onclick", "delivery_check(this, '" + n + "')");
                    $(elm).attr("class", "after_button");
                    $(elm).text("상품 인계");
                    alert('배송 중으로 변경되었습니다.');
                }
            },
            error: function(request,status,error){
                alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
            },
        });
    }

</script>

{% endblock body %} 

seller/templates/footer.html
{% load static %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/_nav.css' %}">
{% endblock head %}

<footer>
    <div class="section-container footer-container">
        <div class="container">
            <div class="row">
                    <div class="col-md-4" align="center">
                        <a href="{% url 'seller:main' %}">| 판매자 메인</a>
                    </div>

                    <div class="col-md-4" align="center">
                        <a href="{% url 'customer:main' %}"><img width="130px" src="{% static 'images/ab_logo.png' %}"></a>
                    </div>

                    <div class="col-md-4" align="center">
                        <h5>만든 사람들</h5>
                        <p>
                            <a href="https://github.com/yjk5309" class="social-round-icon white-round-icon fa-icon" title="yjk">
                            <i class="fa fa-git" aria-hidden="true"></i>
                          </a>
                          <a href="https://github.com/seongwonyang" class="social-round-icon white-round-icon fa-icon" title="swy">
                            <i class="fa fa-git" aria-hidden="true"></i>
                          </a>
                          <a href="https://github.com/cyj199637" class="social-round-icon white-round-icon fa-icon" title="yjj">
                            <i class="fa fa-git" aria-hidden="true"></i>
                          </a>
                        </p>
                        <p><small>ⓒ Alley BookStore. All Rights Reserved.</small></p>
                    </div>
            </div>
        </div>
    </div>
</footer>

seller/templates/notice.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/notice.css' %}">
{% endblock head %}

{% block title %}
공지사항 관리 | alleybookstore
{% endblock title %}

{% block _nav %}
  {% include '_seller_nav.html' %}
{% endblock _nav %}

{% block body %}

<div class="container">
    <div align="center">
        <div class="content">
            <div align="left">
            <h4>현재 등록되어있는 공지사항입니다</h4>
            <p>- 고객분들이 참고할 중요한 내용들을 공지사항으로 등록해주세요<br>
            - 공지사항은 한 건당 100자까지 입력할 수 있습니다<br>
            - 공지사항은 서점 상세 페이지에 최근순으로 최대 3건까지 게시됩니다</p>
            </div>
        <div style="margin-top:30px;">
                <table>
                    <tr>
                        <th width="450px;">공지사항</th>
                        <th width="200px;">날짜</th>
                        <th width="200px;">관리</th>
                    </tr>
                        {% for data in notices %}
                    <tr>
                        <td width="450px;">{{ data.notice }}</td>
                        <td width="200px;">{{ data.date }}</td>
                        <td width="200px;" style="display:flex;">
                            <button type="button" class="button" onclick="notice_modify(this, '{{ data.notice_id }}')">수정</button>
                            <button type="button" class="button" onclick="location.href = '{% url 'seller:notice_delete' data.notice_id %}'">삭제</button>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
        </div>
    </div>
    <hr>
    <div class="form">
        <form class="mt-3" method="post" action='{% url "seller:notice" %}' enctype="multipart/form-data">{% csrf_token %}
            <input type="hidden" id="notice_id" name="notice_id" value="">
            <textarea cols="90" rows="5" id="notice" name="notice" value="" maxlength="100" required></textarea>
            <button id="btn" type="submit" class="btn btn-primary"><span>등록</span></button>
            <button class="btn btn-primary" >취소</button>
        </form>
    </div>
    </div>
</div>
{% block footer %}
{% include 'footer.html' %}
{% endblock footer  %}

<script>
document.addEventListener("DOMContentLoaded", function (event) {
    navActivePage();
});

function notice_modify(elm, n) {
    $.ajax({
        url: "{% url 'seller:notice_modify_ajax' 1 %}".replace("1",n),
        data: {'csrfmiddlewaretoken': '{{csrf_token}}'},
        dataType: "json",
        type: "GET",
        success: function(response){
            $("#notice").val(response.notice_info.notice);
            $("#notice_id").attr('value',response.notice_info.notice_id);

        },
        error: function(request,status,error){
            alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
        },
    });
    $("span").text("수정");

}

</script>

<script type="text/javascript" src="./main.41beeca9.js"></script>
<script src="http://code.jquery.com/jquery-latest.js"></script>

{% endblock body %}

seller/templates/review_manage.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/review.css' %}">
{% endblock head %}

{% block title %}
리뷰 관리 | alleybookstore
{% endblock title %}

{% block _nav %}
  {% include '_seller_nav.html' %}
{% endblock _nav %}

{% block body %}
<div class="container">
    <div class="row justify-content-center align-items-center">
        <div class="flex">
            <div align="center">
                <h3>총 평점 평균</h3>
                <hr>
                <b style="color:gold; align:right; font-size:30px;">
                        {% if avg.star == 2 or avg.star == 1 %}★☆☆☆☆
                        {% elif avg.star == 4 or avg.star == 3 %}★★☆☆☆
                        {% elif avg.star == 6 or avg.star == 5 %}★★★☆☆
                        {% elif avg.star == 8 or avg.star == 7 %}★★★★☆
                        {% elif avg.star == 10 or avg.star == 9 %}★★★★★
                        {% endif %}
                    </b>
                <h4>{{ avg.avg }}</h4>
            </div>
            <div>
                <h3 align="center">BEST 3</h3>
                {% for best in best %}
                <hr>
                <h4>{{ best.rank }}</h4>
                <div class="flex">
                    <img class="img" src="{{best.book_img}}">
                    <div class="flex-2" align="center">
                    <p>{{ best.book_name }}</p>
                    <p>평점 {{ best.avg }}</p>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div>
                <h3 align="center">WORST 3</h3>
                {% for worst in worst %}
                <hr>
                <h4>{{ worst.rank }}</h4>
                <div class="flex">
                    <img class="img" src="{{worst.book_img}}">
                    <div class="flex-2" align="center">
                    <p>{{ worst.book_name }}</p>
                    <p>평점 {{ worst.avg }}</p>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <div id="top" style="height:100px;">
        </div>
<hr>
        <h3>리뷰 최신순</h3>
        {% for review in lately_review %}
        <div>
            <div class="review">
                <p>{{ review.title }}</p>
                <b style="color:gold; align:right" id="review_score" name="review_score" >
                    {% if review.evaluate_score == 2 %}★☆☆☆☆
                    {% elif review.evaluate_score == 4 %}★★☆☆☆
                    {% elif review.evaluate_score == 6 %}★★★☆☆
                    {% elif review.evaluate_score == 8 %}★★★★☆
                    {% elif review.evaluate_score == 10 %}★★★★★
                    {% endif %}
                </b>
                <p>{{ review.user_id }}</p>
                <p>{{ review.date }}</p>
            </div>
            <p> {{ review.content }} </p>
            {% if review.answer == None %}
            <button class="button" onclick="modal(this)" type="button">답변 달기</button>
            {% else %}
            <p style="margin-left:50px;">→ 답변: {{ review.answer }}</p>
            <button class="button" onclick="modify(this, '{{ review.id }}')" type="button">수정</button>
            {% endif %}
            <div>
                <div id="modal" class="modal">
                    <form class="mt-3" method="post" enctype="multipart/form-data" action='{% url "seller:review_answer" %}'>{% csrf_token %}
                        <textarea cols="50" rows="3" id="answer" name="answer" placeholder="리뷰에 대한 답변을 달아주세요"></textarea>
                        <input type="hidden" id="review_id" name="review_id" value="{{ review.id }}">
                        <button class="button-2" type="submit">작성</button>
                    </form>
                    <button class="button" onclick="closeModal()" type="button">닫기</button>
                </div>
            </div>
        </div>
        {% endfor %}
        <a class="top" href="#top">TOP</a>
    </div>
</div>

{% block footer %}
{% include 'footer.html' %}
{% endblock footer %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript" src="https://code.jquery.com/jquery-1.12.4.min.js" ></script>
<script type="text/javascript">
function modal(elm) {
    $(elm).parent().children().children().show();
}

function closeModal() {
    $('.modal').hide();
};

function modify(elm, n) {
    $.ajax({
        url: "{% url 'seller:answer_modify_ajax' 1 %}".replace("1",n),
        data: {'csrfmiddlewaretoken': '{{csrf_token}}'},
        dataType: "json",
        type: "GET",
        success: function(response){
            $(elm).next().children().children().children().val(response.answer_info.answer);
            $(elm).next().children().children().children().next().attr('value',response.answer_info.id);
            $(elm).parent().children().children().show();
        },
        error: function(request,status,error){
            alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
        },
    });

}
</script>

{% endblock body %}

seller/templates/seller_main.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/seller_main.css' %}">
{% endblock head %}
{% block title %}
판매자 홈 | alleybookstore
{% endblock title %}
{% block _nav %}
  {% include '_seller_nav.html' %}
{% endblock _nav %}
{% block body %}
    {% if user.is_authenticated %}
<div class="container">
    <div class="seller_flex">
        <div class="seller_main">
            <b style="color:purple; margin-left:10px; font-size:20px">| <b style="color:orange">판매 현황</b>
            </b>
            <table class="type04">
                <tr>
                    <th scope="row" onclick="location.href='{% url 'seller:order_check' %}'">주문확인 요청</th>
                </tr>
                <tr>
                    <th scope="row" onclick="location.href='{% url 'seller:delivery_check' %}'">배송 & 구매확정전</th>
                </tr>
                <tr>
                    <th scope="row" onclick="location.href='{% url 'seller:settlement_check' %}'">정산 조회</th>
                </tr>
                <tr>
                    <th scope="row" onclick="location.href='{% url 'seller:monthly_settlement' %}'">월별 정산서</th>
                </tr>
            </table>
        </div>

        <div class="seller_main">
            <b style="color:purple; margin-left:10px; font-size:20px">| <b style="color:orange">상품 관리</b>
           </b>
            <table class="type04">
                <tr>
                    <th scope="row" onclick="location.href='{% url 'seller:product_register' %}'">상품 등록</th>
                </tr>
                <tr>
                    <th scope="row" onclick="location.href='{% url 'seller:product_list' %}'">상품 및 재고 관리</th>
                </tr>
            </table>
        </div>
        <div class="seller_main">
            <b style="color:purple; margin-left:10px; font-size:20px">| <b style="color:orange">반품 접수 내역</b>
           </b>
            <table class="type04">
                <tr>
                    <th scope="row" onclick="location.href='{% url 'seller:order_return' 'new' %}'">신규 접수</th>
                </tr>
                <tr>
                    <th scope="row" onclick="location.href='{% url 'seller:order_return' 'complete' %}'">반품 완료</th>
                </tr>
            </table>
        </div>
    </div>

    <div class="seller_flex" style="margin-bottom:50px">
        <div class="seller_main">
            <b style="color:purple; margin-left:10px; font-size:20px">| <b style="color:orange">게시판</b>
           </b>
            <table class="type04">
                <tr>
                    <th scope="row" onclick="location.href='{% url 'seller:notice' %}'">서점 공지사항</th>
                </tr>
                <tr>
                    <th scope="row" onclick="location.href='{% url 'seller:review_manage' %}'">리뷰 관리</th>
                </tr>
                <tr>
                    <th scope="row" onclick="location.href='{% url 'seller:frequent_question' %}'">Q&A</th>
                </tr>
            </table>
        </div>
    </div>
</div>
    {% else %}
    <div class="not_login_flex" style="margin-bottom:50px">
        <div class="seller_main" style="margin-left:500px; text-align:center">
            <br><b style="font-size:30px"># ALLEY BOOKSTORE Shop Manger</b><br>
            <button class="button">서점등록</button>
            <div><img class="seller_main_img" width="500px" height="400px" src="{% static 'images/not_login_main.jpg' %}"></div>
        </div>
    </div>
    {% endif %}
{% block footer %}
{% include 'footer.html' %}
{% endblock footer  %}
<script>
  document.addEventListener("DOMContentLoaded", function (event) {
    navActivePage();
  });
</script>
<script type="text/javascript" src="./main.41beeca9.js"></script>
{% endblock body %}