alleybookstore/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.urls.conf import include


urlpatterns = [
    path('admin/', admin.site.urls),

    re_path(r'^customer_accounts/', include('customer_accounts.urls')),
    re_path(r'^', include('customer.urls')),
    re_path(r'^seller/', include('seller.urls')),
    re_path(r'^seller_accounts/', include('seller_accounts.urls')),
]

customer/urls.py
from django.urls import re_path
from .splitviews import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'customer'

urlpatterns = [
    re_path(r'^$', MainView, name='main'),
    re_path(r'^bookstore/$', SearchStoreView, name='search_store'),
    re_path(r'^bookstore/region/$', RegionSearchView, name='region_search'),
    re_path(r'^bookstore/keyword/$', KeywordSearchView, name='keyword_search'),
    re_path(r'^bookstore/(?P<store_id>\d+)/$', BookStoreDetailView, name='bookstore_detail'),
    re_path(r'^book/$', SearchBookView, name='search_book'),
    re_path(r'^book-list/$', SearchBookResultView, name='search_book_result'),
    re_path(r'^mypage/$', MyPageView, name='mypage'),
    re_path(r'^ajax-city/$', AjaxGetCityView, name='ajax_get_city'),
    re_path(r'^book/(?P<book_isbn>\d+)/(?P<store_id>\d+)/$', BookDetailView, name='book_detail'),
    re_path(r'^book/(?P<book_isbn>\d+)/(?P<store_id>\d+)/customer/$', BookLikeView, name='book_like'),
    re_path(r'^favorite/(?P<store_id>\d+)/$', FavoriteView, name='favorite'),
    re_path(r'^unfavorite/(?P<store_id>\d+)/$', UnfavoriteView, name='unfavorite'),
    re_path(r'^review/(?P<book_isbn>\d+)/(?P<store_id>\d+)/$', BookReviewView, name='book_review'),
    re_path(r'^review/(?P<review_id>\d+)/user/$', BookReviewDeleteView, name='book_review_delete'),
    re_path(r'^review/(?P<review_id>\d+)/modify/$', BookReviewModifyView, name='book_review_modify'),
    re_path(r'^review-ajax-recent/(?P<book_isbn>\d+)/$', AjaxReviewRecentView, name='ajax_review_recent'),
    re_path(r'^review-ajax-highScore/(?P<book_isbn>\d+)/$', AjaxReviewHighScoreView, name='ajax_review_high_score'),
    re_path(r'^basket/(?P<book_isbn>\d+)/(?P<store_id>\d+)/$', BookBasketInsertView, name='book_basket_insert'),
    re_path(r'^basket/(?P<book_isbn>\d+)/session/$', BookBasketDeleteView, name='book_basket_delete'),
    re_path(r'^book/category/$', CategoryView, name='category'),
    re_path(r'^book/category/(?P<main_category_id>\d+)/$', CategoryResultView, name='category_book'),
    re_path(r'^order-sheet/(?P<book_isbn>\d+)/(?P<store_id>\d+)/$', OrderSheetView, name='order_sheet'),
    re_path(r'^order-sheet/cart/$', OrderSheetCartView, name='order_sheet_cart'),
    re_path(r'^order-sheet/create/$', OrderCreateView, name='order'),
    re_path(r'^order-confirm/(?P<order_num>\d+)/$', OrderConfirmView, name='order_confirm'),
    re_path(r'^order-detail/(?P<order_num>\d+)/$', OrderDetailView, name='order_detail'),
    re_path(r'^order-history/$', OrderHistoryView, name='order_history'),
    re_path(r'^bookstore/book-list/$', SearchBookInStoreView, name='search_book_in_store'),
    re_path(r'^mypage_basket/$', CustomerBasketView, name='mypage_basket'),
    re_path(r'^order-decision/(?P<order_num>\d+)/$', OrderDecisionView, name='order_decision'),
    re_path(r'^order-cancel/(?P<order_num>\d+)/$', OrderCancelView, name='order_cancel'),
    re_path(r'^product-return/(?P<order_id>\d+)/$', ProductReturnView, name='product_return'),
    re_path(r'^frequently-question/(?P<store_id>\d+)/$', FrequentQuestionView, name='frequent_question'),
    re_path(r'^individual-question/(?P<store_id>\d+)/$', IndividualQuestionView, name='individual_question'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer_accounts/urls.py
from django.urls import re_path
from .splitviews import *

app_name = 'customer_accounts'

urlpatterns = [
    re_path(r'^login/$', LoginView, name='login'),
    re_path(r'^register/$', RegisterView, name='register'),
    re_path(r'^user-info/(?P<user_id>\d+)/$', InfoModifyView, name='info_modify'),
    re_path(r'^password/(?P<user_id>\d+)/$', PasswordModifyView, name='password_modify'),
    re_path(r'^logout/$', LogoutView, name='logout'),
    re_path(r'^user-info/$', InfoManageView, name='info_manage'),
    re_path(r'^password/$', PasswordCheckView, name='password_check'),
    re_path(r'^secede/$', UserDeleteView, name='user_delete'),
]

seller/urls.py
from django.urls import re_path
from .splitviews import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'seller'

urlpatterns = [
    re_path(r'^$', MainView, name='main'),
    re_path(r'^product/$', ProductListView, name='product_list'),
    re_path(r'^product/book-list$', SearchBookInManageView, name='search_book_in_manage'),
    re_path(r'^product/book-delete/(?P<store_id>\d+)/(?P<isbn>\d+)/$', ProductDeleteView, name='book_delete'),
    re_path(r'^product-modify/$', ProductModifyView, name='book_modify'),
    re_path(r'^product-modify-ajax/(?P<isbn>\d+)/$', AjaxGetProductInfoView, name='book_modify_ajax'),
    re_path(r'^product-register/$', ProductRegisterView, name='product_register'),
    re_path(r'^book-ajax/$', SearchBookAjaxView, name='ajax_book_search'),
    re_path(r'^order/$', OrderCheckView, name='order_check'),
    re_path(r'^pay-check-ajax/(?P<order_num>\d+)/$', PayCheckAjaxView, name='pay_check_ajax'),
    re_path(r'^order-detail-ajax/(?P<order_num>\d+)/$', OrderDetailView, name='order_detail_ajax'),
    re_path(r'^order-return/(?P<click_case>[ㄱ-힣a-zA-Z0-9-_.]*)/$', OrderReturnView, name='order_return'),
    re_path(r'^order-return-check-ajax/(?P<return_id>\d+)/$', OrderReturnCheckAjaxView, name='order_return_check_ajax'),
    re_path(r'^order-return-reject/(?P<return_id>\d+)/$', OrderReturnRejectView, name='order_return_reject'),
    re_path(r'^order-return-reject-compl-ajax/(?P<return_id>\d+)/$', OrderReturnRejectCompAjaxlView, name='order_return_reject_compl_ajax'),
    re_path(r'^book-register/$', BookRegisterView, name='book_register'),
    re_path(r'^delivery/$', DeliveryCheckView, name='delivery_check'),
    re_path(r'^delivery-ajax/(?P<order_num>\d+)/$', DeliveryCheckAjaxView, name='delivery_check_ajax'),
    re_path(r'^notice/$', NoticeForCustomerView, name='notice'),
    re_path(r'^notice-delete/(?P<notice_id>\d+)/$', NoticeDeleteView, name='notice_delete'),
    re_path(r'^notice-modify-ajax/(?P<notice_id>\d+)/$', AjaxGetNoticeView, name='notice_modify_ajax'),
    re_path(r'^settlement/$', SettlementCheckView, name='settlement_check'),
    re_path(r'^monthly-settlement/$', MonthlySettlementView, name='monthly_settlement'),
    re_path(r'^frequent-question/$', FrequentQuestionView, name='frequent_question'),
    re_path(r'^frequent-question-delete/(?P<faq_id>\d+)/$', FrequentQuestionDeleteView, name='frequent_question_delete'),
    re_path(r'^frequent-question-modify/(?P<faq_id>\d+)/$', FrequentQuestionModifyView, name='frequent_question_modify'),
    re_path(r'^individual-question/(?P<store_id>\d+)/$', IndividualQuestionView, name='individual_question'),
    re_path(r'^individual-question-answer/(?P<question_id>\d+)/$', IndividualQuestionAnswerView, name='individual_question_answer'),
    re_path(r'^review/$', ReviewManageView, name='review_manage'),
    re_path(r'^review-answer/$', ReviewAnswerView, name='review_answer'),
    re_path(r'^review-answer-ajax/(?P<review_id>\d+)/$', AjaxGetReviewAnswerView, name='answer_modify_ajax'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seller_accounts/urls.py
from django.urls import re_path
from .splitviews import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'seller_accounts'

urlpatterns = [
    re_path(r'^seller_register/$', SellerRegisterView, name='seller_register'),
    re_path(r'^bookstore_register/$', BookStoreRegisterView, name='bookstore_register'),
    re_path(r'^shipping_info_register/$', ShippingInfoRegisterView, name='shipping_info_register'),
    re_path(r'^seller_login/$', SellerLoginView, name='seller_login'),
    re_path(r'^seller_info/$', SellerInfoView, name='seller_info'),
    re_path(r'^seller_info/bookstore/(?P<user_id>\d+)/$', BookstoreModifyView, name='bookstore_modify'),
    re_path(r'^seller_info/shipping_info/$', ShippingInfoModifyView, name='shipping_info_modify'),
    re_path(r'^secede/$', SellerDeleteView, name='seller_delete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer_accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver

class User(AbstractUser):
    birth_date = models.DateField(null=True, blank=True)
    phone_number = models.CharField(max_length=150, blank=True)
    address = models.TextField(max_length=500, blank=True)
    # 1은 관리자, 2는 구매자, 3은 판매자
    user_type = models.IntegerField(default=2, blank=True)

customer_accounts/templates/_nav.html
{% load static %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/_nav.css' %}">
{% endblock head %}
<header>
  <nav class="navbar  navbar-fixed-top navbar-default">
    <div class="container">
      <div class="collapse navbar-collapse" id="navbar-collapse-uarr" >
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'customer:main' %}" title="" class="active">Home</a></li>
          <li><a href="{% url 'customer:category' %}" title="">카테고리</a></li>
          <li><a href="{% url 'customer:search_book' %}" title="">책 검색</a></li>
          <li><a href="{% url 'customer:search_store' %}" title="">서점 검색</a></li>
          {% if user.is_authenticated and user.user_type == 2 %}
            <li><a href="{% url 'customer:mypage' %}" title="">마이페이지</a></li>
            <li><a href="{% url 'customer:mypage_basket' %}" title="">장바구니</a></li>
            <li>
              <p>
                <a href="{% url 'customer_accounts:logout' %}" class="btn btn-primary navbar-btn" title="">로그아웃</a>
              </p>
            </li>
          {% else %}
            <li>
              <p>
                <a href="{% url 'customer_accounts:login' %}" class="btn btn-primary navbar-btn" title="">로그인</a>
              </p>
            </li>
          {% endif %}

        </ul>
      </div>
    </div>
  </nav>
</header>

customer_accounts/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="UTF-8">
  <meta content="IE=edge" http-equiv="X-UA-Compatible">
  <meta content="width=device-width,initial-scale=1" name="viewport">
  <meta content="description" name="description">
  <meta name="google" content="notranslate" />
  <meta content="Mashup templates have been developped by Orson.io team" name="author">

  <!-- Disable tap highlight on IE -->
  <meta name="msapplication-tap-highlight" content="no">

  <link href="./assets/apple-touch-icon.png" rel="apple-touch-icon">
  <link href="./assets/favicon.ico" rel="icon">

  <link rel="stylesheet" type="text/css" href="{% static 'css/accounts.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/_nav.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

  <title>
    {% block title %}
    {% endblock title %}
  </title>
<script src="https://kit.fontawesome.com/0b02921f0e.js" crossorigin="anonymous"></script>
  {% block head %}
  {% endblock head %}
</head>
<body>
    {% block _nav %}
    {% endblock _nav %}

    {% block body %}
    {% block footer %}
    {% endblock footer %}
    {% endblock body %}
</body>
</html>

customer_accounts/templates/footer.html
{% load static %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/_nav.css' %}">
{% endblock head %}

<footer>
    <div class="section-container footer-container">
        <div class="container">
            <div class="row">
                    <div class="col-md-4" align="center">
                        {% if user.is_authenticated and user.user_type == 3 %}
                        <a href="{% url 'seller:main' %}">| 판매자 페이지</a>
                        {% else %}
                        <a href="{% url 'seller_accounts:seller_login' %}">| 판매자 페이지</a>
                        {% endif %}
                    </div>

                    <div class="col-md-4" align="center">
                        <a href="{% url 'customer:main' %}"><img width="130px" src="{% static 'images/ab_logo.png' %}"></a>
                    </div>

                    <div class="col-md-4" align="center">
                        <h5>만든 사람들</h5>
                        <p>
                            <a href="https://github.com/yjk5309" class="social-round-icon white-round-icon fa-icon" title="yjk">
                            <i class="fa fa-git" aria-hidden="true"></i>
                          </a>
                          <a href="https://github.com/seongwonyang" class="social-round-icon white-round-icon fa-icon" title="swy">
                            <i class="fa fa-git" aria-hidden="true"></i>
                          </a>
                          <a href="https://github.com/cyj199637" class="social-round-icon white-round-icon fa-icon" title="yjj">
                            <i class="fa fa-git" aria-hidden="true"></i>
                          </a>
                        </p>
                        <p><small>ⓒ Alley BookStore. All Rights Reserved.</small></p>
                    </div>
            </div>
        </div>
    </div>
</footer>

customer_accounts/templates/info_modify.html
    <div class="row justify-content-center align-items-center">
        <div style="margin-top:100px;">
        <div class="card">
          <h4 class="card-header">회원정보 수정</h4>
        <div class="card-body">
        <div class="text-center">
            {% if messages %}
                {% for message in messages %}
                  <p style="color:red"> {{message.message}} </p>
                {% endfor %}
            {% endif %}
          <img class="" src="">
        </div>
        <form class="mt-3" method="post" action='{% url "customer_accounts:info_modify" user.id %}'>{% csrf_token %}
            <div class="form-group">
              <input type="text" class="form-control" id="name" name="name" value="{{ user.first_name }}">
            </div>
            <div class="form-group">
              <input type="text" class="form-control" id="user_id" name="user_id" value="{{ user.username }}">
            </div>
            <div class="form-group">
              <input type="email" class="form-control" id="e_mail" name="e_mail" value="{{ user.email }}">
            </div>
            <div class="form-group">
              <input type="tel" class="form-control" id="phone_number" name="p_number"
                     pattern="(010)-\d{3,4}-\d{4}" value="{{ user.phone_number }}">
            </div>
            <div class="form-group">
              <input type="text" class="form-control" id="address" name="address" value="{{ user.address }}">
            </div>
            <button type="submit" class="btn btn-primary" onclick="user_info_modify()">수정 완료</button>
        </form>
        </div>
        </div>
        </div>
    </div>

<script type="text/javascript">
    function user_info_modify(){
        if (confirm("입력한 정보를 수정하시겠습니까?") == true){
            document.form.submit();
        }else{
            alert('취소되었습니다.');
            event.preventDefault();
        }
    }

    window.onpageshow = function(event) {
        if ( event.persisted || (window.performance && window.performance.navigation.type == 2)) {
            // Back Forward Cache로 브라우저가 로딩될 경우 혹은 브라우저 뒤로가기 했을 경우
            alert('제출 양식이 만료되었습니다.');
            history.back();
        }
    }
</script>

customer_accounts/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/accounts.css' %}">
{% endblock head %}

{% block title %}
사용자 로그인 | alleybookstore
{% endblock title %}

{% block _nav %}
  {% include '_nav.html' %}
{% endblock _nav %}

{% block body %}
<div class="container">
    <div class="row justify-content-center align-items-center">
        <div style="margin-top:100px;">
        <div class="card">
          <h4 class="card-header">로그인</h4>
        <div class="card-body">
        <div class="text-center">
            {% if messages %}
                {% for message in messages %}
                  <p style="color:red"> {{message.message}} </p>
                {% endfor %}
            {% endif %}
          <img class="" src="">
        </div>
        <form class="mt-3" method="post" action='{% url "customer_accounts:login" %}'>{% csrf_token %}
            <div class="form-group">
              <input type="text" class="form-control" id="user_id" name="user_id" placeholder="사용자 ID">
            </div>
            <div class="form-group">
              <input type="password" class="form-control" id="user_pw" name="user_pw" placeholder="비밀번호">
            </div>
            <button type="submit" class="btn btn-primary" onclick="">Login</button>
        </form>
        </div>
        </div>
        <div class="card mt-2">
        <div class="text-center mt-3">
          <p>계정이 없으신가요? <a href='{% url "customer_accounts:register" %}'>회원가입</a></p>
          <p>판매자 이신가요? <a href='{% url "seller_accounts:seller_register" %}'>판매자 회원가입</a></p>
        </div>
        </div>
        </div>
    </div>
</div>

{% block footer %}
{% include 'footer.html' %}
{% endblock footer %}

{% endblock body %}

customer_accounts/templates/password_check.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/accounts.css' %}">
{% endblock head %}

{% block title %}
마이페이지 | alleybookstore
{% endblock title %}

{% block _nav %}
  {% include '_nav.html' %}
{% endblock _nav %}

{% block body %}
    <div class="row justify-content-center align-items-center">
        <div style="margin-top:100px;">
        <div class="card">
          <h4 class="card-header">비밀번호 확인</h4>
        <div class="card-body">
        <div class="text-center">
            {% if messages %}
                {% for message in messages %}
                  <p style="color:red"> {{message.message}} </p>
                {% endfor %}
            {% endif %}
          <img class="" src="">
        </div>
        <form class="mt-3" method="post" action='{% url "customer_accounts:password_check" %}'>{% csrf_token %}
            <div class="form-group">
              <input type="password" class="form-control" id="password" name="password" placeholder="본인 확인을 위해 비밀번호를 입력해주세요.">
            </div>
            <button type="submit" class="btn btn-primary" onclick="">완료</button>
        </form>
        </div>
        </div>
        </div>
    </div>

<div class="pw_footer">
<script type="text/javascript">
    window.onpageshow = function(event) {
        if ( event.persisted || (window.performance && window.performance.navigation.type == 2)) {
            // Back Forward Cache로 브라우저가 로딩될 경우 혹은 브라우저 뒤로가기 했을 경우
            alert('제출 양식이 만료되었습니다.');
            history.back();
        }
    }
</script>
{% block footer %}
{% include 'footer.html' %}
{% endblock footer %}
</div>

{% endblock body %}

customer_accounts/templates/password_modify.html
    <div class="row justify-content-center align-items-center">
        <div style="margin-top:100px;">
        <div class="card">
          <h4 class="card-header">비밀번호 변경</h4>
        <div class="card-body">
        <div class="text-center">
            {% if messages %}
                {% for message in messages %}
                  <p style="color:red"> {{message.message}} </p>
                {% endfor %}
            {% endif %}
          <img class="" src="">
        </div>
        <form class="mt-3" method="post" action='{% url "customer_accounts:password_modify" user.id %}'>{% csrf_token %}
            <div class="form-group">
              <input type="password" class="form-control" id="current_password" name="current_password" placeholder="현재 비밀번호">
            </div>
            <div class="form-group">
              <input type="password" class="form-control" id="new_password" name="new_password" placeholder="새 비밀번호">
            </div>
            <div class="form-group">
              <input type="password" class="form-control" id="check_new_password" name="check_new_password" placeholder="새 비밀번호 확인">
            </div>
            <button type="submit" class="btn btn-primary" onclick="password_modify()">수정 완료</button>
        </form>
        </div>
        </div>
        </div>
    </div>

<script type="text/javascript">
    function password_modify(){
        if (confirm("비밀번호를 변경하시겠습니까?") == true){
            document.form.submit();
        }else{
            event.preventDefault();
        }
    }

    window.onpageshow = function(event) {
        if ( event.persisted || (window.performance && window.performance.navigation.type == 2)) {
            // Back Forward Cache로 브라우저가 로딩될 경우 혹은 브라우저 뒤로가기 했을 경우
            alert('제출 양식이 만료되었습니다.');
            history.back();
        }
    }

</script>

customer_accounts/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/accounts.css' %}">
{% endblock head %}

{% block title %}
사용자 회원가입 | alleybookstore
{% endblock title %}

{% block _nav %}
  {% include '_nav.html' %}
{% endblock _nav %}

{% block body %}
<div class="container">
    <div class="row justify-content-center align-items-center">
        <div style="margin-top:100px;">
        <div class="card">
          <h4 class="card-header">사용자 회원가입</h4>
        <div class="card-body">
        <div class="text-center">
            {% if messages %}
                {% for message in messages %}
                  <p style="color:red"> {{message.message}} </p>
                {% endfor %}
            {% endif %}
          <img class="" src="">
        </div>
        <form class="mt-3" method="post" action='{% url "customer_accounts:register" %}'>{% csrf_token %}
            <div class="form-group">
              <input type="text" class="form-control" id="name" name="name" placeholder="성명" required>
            </div>
            <div class="form-group">
              <input type="text" class="form-control" id="user_id" name="user_id" placeholder="사용자 ID" required>
            </div>
            <div class="form-group">
              <input type="password" class="form-control" id="user_pw" name="user_pw" placeholder="비밀번호" required>
            </div>
            <div class="form-group">
              <input type="password" class="form-control" id="user_2nd_pw" name="user_2nd_pw" placeholder="비밀번호 재입력" required>
            </div>
            <div class="form-group">
              <input type="email" class="form-control" id="e_mail" name="e_mail" placeholder="E-Mail" required>
            </div>
            <div class="form-group">
              <input type="tel" class="form-control" id="p_number" name="p_number"
                     pattern="(010)-\d{3,4}-\d{4}" placeholder="휴대전화 ex) 010-1234-1234" required>
            </div>
            <div class="form-group">
              <input type="text" class="form-control" id="address" name="address" placeholder="주소">
            </div>
            <button type="submit" class="btn btn-primary" onclick="alert('회원가입을 완료하시겠습니까?')">회원가입</button>
        </form>
        </div>
        </div>
        <div class="card mt-2">
        <div class="text-center mt-3">
          <p>이미 계정이 있으신가요? <a href='{% url "customer_accounts:login" %}'>로그인</a></p>
        </div>
        </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    window.onpageshow = function(event) {
        if ( event.persisted || (window.performance && window.performance.navigation.type == 2)) {
            // Back Forward Cache로 브라우저가 로딩될 경우 혹은 브라우저 뒤로가기 했을 경우
            alert('제출 양식이 만료되었습니다.');
            history.back();
        }
    }
</script>
{% block footer %}
{% include 'footer.html' %}
{% endblock footer %}

{% endblock body %}

customer_accounts/templates/user_delete.html
    <div class="row justify-content-center align-items-center">
        <div style="margin-top:100px;">
        <div class="card">
          <h4 class="card-header">회원탈퇴</h4>
        <div class="card-body">

        <div class="text-center mt-3">
           <b>본인확인을 위해 ID와 비밀번호를 입력해주세요</b><br><br>
        </div>

        <div class="text-center">
            {% if messages %}
                {% for message in messages %}
                  <p style="color:red"> {{message.message}} </p>
                {% endfor %}
            {% endif %}
          <img class="" src="">
        </div>

        <form class="mt-3" method="post" action='{% url "customer_accounts:user_delete" %}'>{% csrf_token %}
            <div class="form-group">
              <input type="text" class="form-control" id="id" name="id" placeholder="ID">
            </div>
            <div class="form-group">
              <input type="password" class="form-control" id="password" name="password" placeholder="비밀번호">
            </div>
            <button type="submit" class="btn btn-primary" onclick="user_delete()">회원탈퇴</button>
        </form>
        </div>
        </div>
        </div>
    </div>


<script type="text/javascript">
    function user_delete(){
        if (confirm("정말로 탈퇴하시겠습니까?") == true){
            document.form.submit();
        }else{
            event.preventDefault();
        }
    }

    window.onpageshow = function(event) {
        if ( event.persisted || (window.performance && window.performance.navigation.type == 2)) {
            // Back Forward Cache로 브라우저가 로딩될 경우 혹은 브라우저 뒤로가기 했을 경우
            alert('제출 양식이 만료되었습니다.');
            history.back();
        }
    }

</script>