alleybookstore/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.urls.conf import include


urlpatterns = [
    path('admin/', admin.site.urls),

    re_path(r'^customer_accounts/', include('customer_accounts.urls')),
    re_path(r'^', include('customer.urls')),
    re_path(r'^seller/', include('seller.urls')),
    re_path(r'^seller_accounts/', include('seller_accounts.urls')),
]

customer/urls.py
from django.urls import re_path
from .splitviews import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'customer'

urlpatterns = [
    re_path(r'^$', MainView, name='main'),
    re_path(r'^bookstore/$', SearchStoreView, name='search_store'),
    re_path(r'^bookstore/region/$', RegionSearchView, name='region_search'),
    re_path(r'^bookstore/keyword/$', KeywordSearchView, name='keyword_search'),
    re_path(r'^bookstore/(?P<store_id>\d+)/$', BookStoreDetailView, name='bookstore_detail'),
    re_path(r'^book/$', SearchBookView, name='search_book'),
    re_path(r'^book-list/$', SearchBookResultView, name='search_book_result'),
    re_path(r'^mypage/$', MyPageView, name='mypage'),
    re_path(r'^ajax-city/$', AjaxGetCityView, name='ajax_get_city'),
    re_path(r'^book/(?P<book_isbn>\d+)/(?P<store_id>\d+)/$', BookDetailView, name='book_detail'),
    re_path(r'^book/(?P<book_isbn>\d+)/(?P<store_id>\d+)/customer/$', BookLikeView, name='book_like'),
    re_path(r'^favorite/(?P<store_id>\d+)/$', FavoriteView, name='favorite'),
    re_path(r'^unfavorite/(?P<store_id>\d+)/$', UnfavoriteView, name='unfavorite'),
    re_path(r'^review/(?P<book_isbn>\d+)/(?P<store_id>\d+)/$', BookReviewView, name='book_review'),
    re_path(r'^review/(?P<review_id>\d+)/user/$', BookReviewDeleteView, name='book_review_delete'),
    re_path(r'^review/(?P<review_id>\d+)/modify/$', BookReviewModifyView, name='book_review_modify'),
    re_path(r'^review-ajax-recent/(?P<book_isbn>\d+)/$', AjaxReviewRecentView, name='ajax_review_recent'),
    re_path(r'^review-ajax-highScore/(?P<book_isbn>\d+)/$', AjaxReviewHighScoreView, name='ajax_review_high_score'),
    re_path(r'^basket/(?P<book_isbn>\d+)/(?P<store_id>\d+)/$', BookBasketInsertView, name='book_basket_insert'),
    re_path(r'^basket/(?P<book_isbn>\d+)/session/$', BookBasketDeleteView, name='book_basket_delete'),
    re_path(r'^book/category/$', CategoryView, name='category'),
    re_path(r'^book/category/(?P<main_category_id>\d+)/$', CategoryResultView, name='category_book'),
    re_path(r'^order-sheet/(?P<book_isbn>\d+)/(?P<store_id>\d+)/$', OrderSheetView, name='order_sheet'),
    re_path(r'^order-sheet/cart/$', OrderSheetCartView, name='order_sheet_cart'),
    re_path(r'^order-sheet/create/$', OrderCreateView, name='order'),
    re_path(r'^order-confirm/(?P<order_num>\d+)/$', OrderConfirmView, name='order_confirm'),
    re_path(r'^order-detail/(?P<order_num>\d+)/$', OrderDetailView, name='order_detail'),
    re_path(r'^order-history/$', OrderHistoryView, name='order_history'),
    re_path(r'^bookstore/book-list/$', SearchBookInStoreView, name='search_book_in_store'),
    re_path(r'^mypage_basket/$', CustomerBasketView, name='mypage_basket'),
    re_path(r'^order-decision/(?P<order_num>\d+)/$', OrderDecisionView, name='order_decision'),
    re_path(r'^order-cancel/(?P<order_num>\d+)/$', OrderCancelView, name='order_cancel'),
    re_path(r'^product-return/(?P<order_id>\d+)/$', ProductReturnView, name='product_return'),
    re_path(r'^frequently-question/(?P<store_id>\d+)/$', FrequentQuestionView, name='frequent_question'),
    re_path(r'^individual-question/(?P<store_id>\d+)/$', IndividualQuestionView, name='individual_question'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer_accounts/urls.py
from django.urls import re_path
from .splitviews import *

app_name = 'customer_accounts'

urlpatterns = [
    re_path(r'^login/$', LoginView, name='login'),
    re_path(r'^register/$', RegisterView, name='register'),
    re_path(r'^user-info/(?P<user_id>\d+)/$', InfoModifyView, name='info_modify'),
    re_path(r'^password/(?P<user_id>\d+)/$', PasswordModifyView, name='password_modify'),
    re_path(r'^logout/$', LogoutView, name='logout'),
    re_path(r'^user-info/$', InfoManageView, name='info_manage'),
    re_path(r'^password/$', PasswordCheckView, name='password_check'),
    re_path(r'^secede/$', UserDeleteView, name='user_delete'),
]

seller/urls.py
from django.urls import re_path
from .splitviews import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'seller'

urlpatterns = [
    re_path(r'^$', MainView, name='main'),
    re_path(r'^product/$', ProductListView, name='product_list'),
    re_path(r'^product/book-list$', SearchBookInManageView, name='search_book_in_manage'),
    re_path(r'^product/book-delete/(?P<store_id>\d+)/(?P<isbn>\d+)/$', ProductDeleteView, name='book_delete'),
    re_path(r'^product-modify/$', ProductModifyView, name='book_modify'),
    re_path(r'^product-modify-ajax/(?P<isbn>\d+)/$', AjaxGetProductInfoView, name='book_modify_ajax'),
    re_path(r'^product-register/$', ProductRegisterView, name='product_register'),
    re_path(r'^book-ajax/$', SearchBookAjaxView, name='ajax_book_search'),
    re_path(r'^order/$', OrderCheckView, name='order_check'),
    re_path(r'^pay-check-ajax/(?P<order_num>\d+)/$', PayCheckAjaxView, name='pay_check_ajax'),
    re_path(r'^order-detail-ajax/(?P<order_num>\d+)/$', OrderDetailView, name='order_detail_ajax'),
    re_path(r'^order-return/(?P<click_case>[ㄱ-힣a-zA-Z0-9-_.]*)/$', OrderReturnView, name='order_return'),
    re_path(r'^order-return-check-ajax/(?P<return_id>\d+)/$', OrderReturnCheckAjaxView, name='order_return_check_ajax'),
    re_path(r'^order-return-reject/(?P<return_id>\d+)/$', OrderReturnRejectView, name='order_return_reject'),
    re_path(r'^order-return-reject-compl-ajax/(?P<return_id>\d+)/$', OrderReturnRejectCompAjaxlView, name='order_return_reject_compl_ajax'),
    re_path(r'^book-register/$', BookRegisterView, name='book_register'),
    re_path(r'^delivery/$', DeliveryCheckView, name='delivery_check'),
    re_path(r'^delivery-ajax/(?P<order_num>\d+)/$', DeliveryCheckAjaxView, name='delivery_check_ajax'),
    re_path(r'^notice/$', NoticeForCustomerView, name='notice'),
    re_path(r'^notice-delete/(?P<notice_id>\d+)/$', NoticeDeleteView, name='notice_delete'),
    re_path(r'^notice-modify-ajax/(?P<notice_id>\d+)/$', AjaxGetNoticeView, name='notice_modify_ajax'),
    re_path(r'^settlement/$', SettlementCheckView, name='settlement_check'),
    re_path(r'^monthly-settlement/$', MonthlySettlementView, name='monthly_settlement'),
    re_path(r'^frequent-question/$', FrequentQuestionView, name='frequent_question'),
    re_path(r'^frequent-question-delete/(?P<faq_id>\d+)/$', FrequentQuestionDeleteView, name='frequent_question_delete'),
    re_path(r'^frequent-question-modify/(?P<faq_id>\d+)/$', FrequentQuestionModifyView, name='frequent_question_modify'),
    re_path(r'^individual-question/(?P<store_id>\d+)/$', IndividualQuestionView, name='individual_question'),
    re_path(r'^individual-question-answer/(?P<question_id>\d+)/$', IndividualQuestionAnswerView, name='individual_question_answer'),
    re_path(r'^review/$', ReviewManageView, name='review_manage'),
    re_path(r'^review-answer/$', ReviewAnswerView, name='review_answer'),
    re_path(r'^review-answer-ajax/(?P<review_id>\d+)/$', AjaxGetReviewAnswerView, name='answer_modify_ajax'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seller_accounts/urls.py
from django.urls import re_path
from .splitviews import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'seller_accounts'

urlpatterns = [
    re_path(r'^seller_register/$', SellerRegisterView, name='seller_register'),
    re_path(r'^bookstore_register/$', BookStoreRegisterView, name='bookstore_register'),
    re_path(r'^shipping_info_register/$', ShippingInfoRegisterView, name='shipping_info_register'),
    re_path(r'^seller_login/$', SellerLoginView, name='seller_login'),
    re_path(r'^seller_info/$', SellerInfoView, name='seller_info'),
    re_path(r'^seller_info/bookstore/(?P<user_id>\d+)/$', BookstoreModifyView, name='bookstore_modify'),
    re_path(r'^seller_info/shipping_info/$', ShippingInfoModifyView, name='shipping_info_modify'),
    re_path(r'^secede/$', SellerDeleteView, name='seller_delete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/models.py
from django.db import models

# Create your models here.

customer/templates/_nav.html
{% load static %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/_nav.css' %}">
{% endblock head %}
<header>
  <nav class="navbar  navbar-fixed-top navbar-default">
    <div class="container">
      <div class="collapse navbar-collapse" id="navbar-collapse-uarr" >
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'customer:main' %}" title="" class="active">Home</a></li>
          <li><a href="{% url 'customer:category' %}" title="">카테고리</a></li>
          <li><a href="{% url 'customer:search_book' %}" title="">책 검색</a></li>
          <li><a href="{% url 'customer:search_store' %}" title="">서점 검색</a></li>
          {% if user.is_authenticated and user.user_type == 2 %}
            <li><a href="{% url 'customer:mypage' %}" title="">마이페이지</a></li>
            <li><a href="{% url 'customer:mypage_basket' %}" title="">장바구니</a></li>
            <li>
              <p>
                <a href="{% url 'customer_accounts:logout' %}" class="btn btn-primary navbar-btn" title="">로그아웃</a>
              </p>
            </li>
          {% else %}
            <li>
              <p>
                <a href="{% url 'customer_accounts:login' %}" class="btn btn-primary navbar-btn" title="">로그인</a>
              </p>
            </li>
          {% endif %}

        </ul>
      </div>
    </div>
  </nav>
</header>

customer/templates/footer.html
{% load static %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/_nav.css' %}">
{% endblock head %}

<footer>
    <div class="section-container footer-container">
        <div class="container">
            <div class="row">
                    <div class="col-md-4" align="center">
                        {% if user.is_authenticated and user.user_type == 3 %}
                        <a href="{% url 'seller:main' %}">| 판매자 페이지</a>
                        {% else %}
                        <a href="{% url 'seller_accounts:seller_login' %}">| 판매자 페이지</a>
                        {% endif %}
                    </div>

                    <div class="col-md-4" align="center">
                        <a href="{% url 'customer:main' %}"><img width="130px" src="{% static 'images/ab_logo.png' %}"></a>
                    </div>

                    <div class="col-md-4" align="center">
                        <h5>만든 사람들</h5>
                        <p>
                            <a href="https://github.com/yjk5309" class="social-round-icon white-round-icon fa-icon" title="yjk">
                            <i class="fa fa-git" aria-hidden="true"></i>
                          </a>
                          <a href="https://github.com/seongwonyang" class="social-round-icon white-round-icon fa-icon" title="swy">
                            <i class="fa fa-git" aria-hidden="true"></i>
                          </a>
                          <a href="https://github.com/cyj199637" class="social-round-icon white-round-icon fa-icon" title="yjj">
                            <i class="fa fa-git" aria-hidden="true"></i>
                          </a>
                        </p>
                        <p><small>ⓒ Alley BookStore. All Rights Reserved.</small></p>
                    </div>
            </div>
        </div>
    </div>
</footer>

customer/templates/main.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
{% endblock head %}

{% block title %}
메인페이지 | alleybookstore
{% endblock title %}

{% block _nav %}
  {% include '_nav.html' %}
{% endblock _nav %}

{% block body %}


<div class="white-text-container background-image-container" style="background-image: url('{% static 'images/main_image.jpg' %}')">
    <div class="opacity"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="flex">
                    <div class="image round fit">
                        <img width="200px" src="{% static 'images/ab_logo.png' %}">
                    </div>
                    <div>
                    <h1>골목 서점</h1>
                    <p>당신 옆에 가장 가까운 친구,<br> 어서오세요 골목 서점입니다</p>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
<div class="section-container border-section-container">
    <div class="container">
            <div class="row">
                <div class="col-md-12 section-container-spacer">
                    <div class="text-center">
                        <h2>이 주의 책</h2>
                        <p> 이번주 제일 인기있었던 책을 알려드려요. </p>
                    </div>
                </div>
                {% for book in books %}
                  <form class="col-md-4" method="get" enctype="multipart/form-data" action='{% url "customer:search_book_result" %}'>
                      <button type="submit">
                          <div align="center">
                            <input type="text" id="title" name="title" value="{{ book.book_name }}">
                          </div>
                          <br>
                            <input type="hidden" id="publisher" name="publisher" value="{{ book.publisher }}">
                            <input type="hidden" id="author" name="author" value="{{ book.author }}">
                          <div align="center">
                              <img align="center" src="{{ book.book_img }}">
                          </div>
                      </button>
                  </form>
                {% endfor %}

            </div>
    </div>
</div>

<div class="section-container border-section-container">
    <div class="container">
            <div class="row">
                <div class="col-md-12 section-container-spacer">
                    <div class="text-center">
                        <h2>이 주의 서점</h2>
                        <p> 이번주 제일 인기있었던 서점을 알려드려요. </p>
                    </div>
                </div>
                {% for store in stores %}
                <div class="col-md-4">
                    <div class="fa-container">
                        <i class="fa fa-heart-o fa-3x" aria-hidden="true"></i>
                    </div>
                    <div class="text-center">
                        <a href="{% url 'customer:bookstore_detail' store.store_id %}" >
                            <h3>{{store.store_name}}</h3>
                        </a>
                    </div>
                    <div align="center">
                        <p>{{store.store_msg}}</p>
                    </div>
                </div>
                {% endfor %}

            </div>
    </div>
</div>

{% block footer %}
{% include 'footer.html' %}
{% endblock footer  %}

<script>
  document.addEventListener("DOMContentLoaded", function (event) {
    navActivePage();
  });
</script>

<!-- Google Analytics: change UA-XXXXX-X to be your site's ID

<script>
  (function (i, s, o, g, r, a, m) {
    i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
      (i[r].q = i[r].q || []).push(arguments)
    }, i[r].l = 1 * new Date(); a = s.createElement(o),
      m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
  })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
  ga('create', 'UA-XXXXX-X', 'auto');
  ga('send', 'pageview');
</script>

-->

<script type="text/javascript" src="./main.41beeca9.js"></script>

{% endblock body %}

customer/templates/mylist.html
{% load static %}
    <div class="tabmenu">
      <ul>
        <li id="tab1" class="btnCon"> <input type="radio" checked name="tabmenu" id="tabmenu1">
          <label for="tabmenu1">즐겨찾기 서점</label>
          <div class="tabCon" >
              <div class="flex">
              {% for store in favorite_stores %}
                        <a href="{% url 'customer:bookstore_detail' store.store_id %}" >
                            <div class="image round fit">
                                {% if store.store_img == None %}
                                <img src="{% static 'images/bookstore_icon.png' %}">
                                {% else %}
                                <img src="{{ store.store_img }}">
                                {% endif %}
                            </div>
                        <p style="font-weight:bold" align="center">{{ store.store_name }}</p>
                        </a>
              {% endfor %}
              </div>
          </div>
        </li>

        <li id="tab2" class="btnCon"><input type="radio" name="tabmenu" id="tabmenu2">
          <label for="tabmenu2">찜한 책</label>
          <div class="tabCon" >
              <div class="flex">
              {% for book in like_books %}
                  <div class="like_list">
                        <a href="{% url 'customer:book_detail' book.isbn book.store_id %}" >
                        <div class="image book">
                            <img align="center" src="{{ book.book_img }}" alt="" />
                        </div>
                        <p style="font-weight:bold;" align="center">{{ book.book_name }}<br>{{ book.store_name }}</p>
                        </a>
                  </div>
              {% endfor %}
              </div>
          </div>
        </li>
      </ul>
    </div>

customer/templates/name_search.html
<form class="mt-3" method="post" enctype="multipart/form-data" action='{% url "customer:keyword_search" %}'>
    {% csrf_token %}
    <input type="text" class="form-control" id="search_store" name="search_store" placeholder="찾고싶은 서점을 검색하세요." required>
    <button type="submit" class="btn btn-primary" onclick="setBounds()">검색</button>
</form>
<br>
<div class="text-center">
    {% if messages %}
    {% for message in messages %}
        <p style="color:red"> {{message.message}} </p>
    {% endfor %}
    {% endif %}
</div>

customer/templates/order_confirm.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/order_sheet.css' %}">
{% endblock head %}

{% block title %}
주문 확인 페이지 | alleybookstore
{% endblock title %}

{% block _nav %}
  {% include '_nav.html' %}
{% endblock _nav %}

{% block body %}
<div class="container">
  <h2>주문이 완료되었습니다</h2>
      <div class="card">
          <h5>주문번호 {{info.order_num}}</h5>
          <hr>
        <h4>주문 상품 정보</h4>
        {% for book in products %}
        <table>
            <tr>
                <td rowspan="2"><img src="{{ book.book_img }}" width="70px" height="100px"></td>
                <td width="200">상품명</td>
                <td width="80">가격</td>
                <td width="200">서점</td>
                <td width="45">수량</td>
            </tr>
            <tr>
                <td width="200">{{book.book_name}}</td>
                <td width="80">{{book.price}}원</td>
                <td width="200">{{book.store_name}}</td>
                <td width="45">{{book.quantity}}권</td>
            </tr>
        </table>
        {% endfor %}
          <hr>
          <h4>주문자 정보</h4>
          <h5>이름   {{info.order_name}}</h5>
          <h5>연락처 {{info.order_p_num}}</h5>
          <h5>주소   {{info.order_address}}</h5>
          {% if payment.payment == 'bank' %}
              <hr>
              <h4>무통장 입금 정보</h4>
              <h5>{{payment.due_date}}까지 입금해주세요</h5>
              {% for info in account_info %}
              <table>
                <tr>
                    <td width="100">서점</td>
                    <td width="100">총 가격</td>
                    <td width="60">은행</td>
                    <td width="130">계좌</td>
                </tr>
                <tr>
                    <td width="100">{{info.store_name}}</td>
                    <td width="100">{{info.price}}원</td>
                    <td width="60">{{info.bank}}</td>
                    <td width="130">{{info.account}}</td>
                </tr>
              </table>
              {% endfor %}
          {% else %}
          {% endif %}
          <button class="btn btn-primary" onclick="location.href='{% url 'customer:mypage' %}'">구매내역 보기</button>
          <button class="btn btn-primary" onclick="location.href='{% url 'customer:main' %}'">홈으로 돌아가기</button>
    </div>
</div>

{% block footer %}
{% include 'footer.html' %}
{% endblock footer  %}

{% endblock body %}

customer/templates/order_detail.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/mypage.css' %}">
{% endblock head %}

{% block title %}
마이페이지 | alleybookstore
{% endblock title %}

{% block _nav %}
  {% include '_nav.html' %}
{% endblock _nav %}

{% block body %}
<div class="container">
<div class="tab_wrap">
  <div class="tab_menu_container">
    <button class="tab_menu_btn on" type="button" onclick="location.href='{% url 'customer:mypage' %}'">주문확인/배송조회</button>
    <button class="tab_menu_btn" type="button">장바구니</button>
    <button class="tab_menu_btn" type="button">마이리스트</button>
    <button class="tab_menu_btn" type="button" onclick="location.href='{% url 'customer_accounts:password_check' %}'" >회원정보</button>
  </div> <!-- tab_menu_container e -->

  <div class="tab_box_container">
    <div class="tab_box on">
      <div class="card">
        <table>
          <tr>
            <th>주문번호</th>
            <td colspan="3">{{order_detail.order_num}}</td>
          </tr>
          <tr>
            <th>주문일</th>
            <td>{{order_detail.buy_date}}</td>
          </tr>
        </table>
<br>
        <table>
          <tr>
            <th>주문하신 분</th>
            <td>{{order_detail.user_name}}</td>
            <th>받으시는 분</th>
            <td>{{order_detail.order_name}}</td>
          </tr>
          <tr>
            <th>배송 주소</th>
            <td colspan="3">{{order_detail.order_address}}</td>
          </tr>
          <tr>
            <th>휴대번호</th>
            <td>{{order_detail.order_p_num}}</td>
            <th>배송메시지</th>
            <td>{{order_detail.order_memo}}</td>
          </tr>
        </table>
<br>
<h4>주문 상품 정보</h4>
        {% for book in products %}
        <table width="650px;" height="120px">
            <tr>
                <td rowspan="2"><img src="{{ book.book_img }}" width="75px" height="100px"></td>
                <td width="200">상품명</td>
                <td width="90">구매가격</td>
                <td width="100">수량</td>
                <td width="180">서점</td>
                <td width="120">배송 상태</td>
            </tr>
            <tr>
                <td width="200">{{book.book_name}}</td>
                <td width="90">{{book.price}}원</td>
                <td width="100">{{book.quantity}}</td>
                <td width="180">{{book.store_name}}</td>
                <td width="140">{{book.order_status}}</td>
                {% if book.order_status == "배송 완료" or book.order_status == "구매확정" and book.return_possible == 1 %}
                    <td width="60"><button class="order_confirm_button1" type="button" onclick="location.href='{% url 'customer:product_return' book.order_product_id %}'">반품신청</button></td>
                {% else %}
                    <td width="60"><button class="none_button" onclick="#"></button></td>
                {% endif %}
            </tr>
        </table>
        {% endfor %}
          <br>
          {% if is_return_reject == 1 %}
            <table>
                <tr>
                    <td width="120px" style="font-weight:bold">책 이름</td>
                    <td style="font-weight:bold; margin-left: 100px">환불 거절사유</td>
                </tr>
                {% for data in return_reject_info %}
                    <tr>
                        <td style="margin-right:50px">{{data.book_name}}</td>
                        {% if data.reject_reason != None %}
                        <td>{{data.reject_reason}}</td>
                        {% elif data.reject_reason == None %}
                        <td style="color:red">답변 미완료</td>
                        {% endif %}
                </tr>
                {% endfor %}
            </table>
            <br>
          {% endif %}
        <table>
          <tr>
            <th>총 주문 금액</th>
            <td>{{order_detail.price}}원</td>
          </tr>
          <tr>
            <th>결제 방법</th>
            <td>{% if order_detail.payment == 'bank' %}
              무통장 입금
            {% else %}
              카드 결제
          {% endif %}</td>
          </tr>
        </table>
            {% if order_status == "결제 대기중" or order_status == "결제 완료" %}
                <br><button class="order_confirm_button1" onclick="order_cancel(this, '{{ order_detail.order_num }}')">결제취소</button>
            {% endif %}
      {% if order_detail.payment == 'bank' %}
              <hr>
              <h4>무통장 입금 정보</h4>
              <h5>{{order_detail.due_date}}까지 입금해주세요</h5>
              {% for info in account_info %}
              <table>
                <tr>
                    <td width="100">서점</td>
                    <td width="100">총 가격</td>
                    <td width="60">은행</td>
                    <td width="130">계좌</td>
                </tr>
                <tr>
                    <td width="100">{{info.store_name}}</td>
                    <td width="100">{{info.price}}원</td>
                    <td width="60">{{info.bank}}</td>
                    <td width="130">{{info.account}}</td>
                </tr>
              </table>
              {% endfor %}
          {% else %}
          {% endif %}
      </div>
    </div>
    <div class="tab_box">{% include 'book_basket.html' %}</div>
    <div class="tab_box">{% include 'mylist.html' %}</div>
  </div> <!-- tab_box_container e -->
</div> <!-- tab_wrap e -->


</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript">
    $('.tab_menu_btn').on('click',function(){
      //버튼 색 제거,추가
      $('.tab_menu_btn').removeClass('on');
      $(this).addClass('on')

      //컨텐츠 제거 후 인덱스에 맞는 컨텐츠 노출
      var idx = $('.tab_menu_btn').index(this);

      $('.tab_box').hide();
      $('.tab_box').eq(idx).show();
    });

    function order_cancel(elm, n){
        if (confirm("결제를 취소하시겠습니까?") == true){
            location.href = "/order-cancel/" + n;
        }else{
            alert('취소되었습니다.');
            event.preventDefault();
        }
    }

</script>

{% block footer %}
{% include 'footer.html' %}
{% endblock footer %}

{% endblock body %}

customer/templates/region_search.html
<form class="mt-3" method="post" enctype="multipart/form-data" action='{% url "customer:region_search" %}'>{% csrf_token %}
    <select name="province" id="province">
        <option>---------- 도 ----------</option>
        {% for province in provinces %}
            <option>{{ province.name }}</option>
        {% endfor %}
    </select>

    <select name="city" id="city">
        <option>---------- 시 ----------</option>
    </select>
    <br>
    <button type="submit" class="btn btn-primary" onclick="setBounds()">검색</button>
</form>
<br>
<div class="text-center">
    {% if messages %}
    {% for message in messages %}
        <p style="color:red"> {{message.message}} </p>
    {% endfor %}
    {% endif %}
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript">
    $(function(){
        $('#province').change(function() {
            var province_name = this.value

            $.ajax({
                type: "POST",
                url: "{% url 'customer:ajax_get_city' %}",
                data: {'province_name': province_name, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                dataType: "json",
                success: function(response){
                    var items = "<option>---------- 시 ----------</option>";
                    for(var i=0; i<response.cities.length; i++){
                        items += ("<option>" + response.cities[i].name  + "</option>")
                    }

                    $("#city").html(items);
                },
                error: function(request, status, error){
                    alert(error);
                },
            });
        });
    });
</script>